"""empty message

Revision ID: 9e4b9b7842b5
Revises: 8742e9b33e5a
Create Date: 2024-09-02 23:26:26.266718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4b9b7842b5'
down_revision = '8742e9b33e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_credits', sa.String(length=120), nullable=False))
        batch_op.drop_column('cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('cost_credits')

    # ### end Alembic commands ###
