"""empty message

Revision ID: b564612ee2ae
Revises: 9e4b9b7842b5
Create Date: 2024-09-02 23:29:38.778939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b564612ee2ae'
down_revision = '9e4b9b7842b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_class', sa.String(length=120), nullable=False))
        batch_op.drop_column('vehicles_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles_class', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('vehicle_class')

    # ### end Alembic commands ###
